import turtle

ed = turtle.Turtle()
edd = turtle.Turtle()
eddd = turtle.Turtle()
edddd = turtle.Turtle()
eddddd = turtle.Turtle()
edddddd = turtle.Turtle()
eddddddd= turtle.Turtle()

ed.shape("turtle")
edd.shape("turtle")
eddd.shape("turtle")
edddd.shape("turtle")
eddddd.shape("turtle")
eddddd.shape("turtle")
edddddd.shape("turtle")

ed.penup()
ed.begin_fill()
ed.color("green")
ed.forward(500)
ed.backward(1000)
ed.right(450)
ed.forward(500)
ed.right(270)
ed.forward(1000)
ed.left(90)
ed.forward(500)
ed.end_fill()
ed.pendown()

edd.penup()
edd.begin_fill()
edd.color("sky blue")
edd.forward(500)
edd.left(90)
edd.forward(1000)
edd.left(90)
edd.forward(1000)
edd.left(90)
edd.forward(500)
edd.forward(500)
edd.end_fill()
edd.pendown()

eddd.penup()
eddd.begin_fill()
eddd.color("saddle brown")
eddd.goto(350, 0)
eddd.left(90)
eddd.forward(250)
eddd.right(90)
eddd.forward(50)
eddd.right(90)
eddd.forward(250)
eddd.end_fill()
eddd.pendown()

edddd.penup()
edddd.begin_fill()
edddd.color("green")
edddd.goto(375, 210)
edddd.circle(100)
edddd.end_fill()

eddddd.penup()
eddddd.begin_fill()
eddddd.color("yellow")
eddddd.goto(-450, 300)
eddddd.circle(200)
eddddd.end_fill()



turtle.exitonclick()