import turtle

ed = turtle.Turtle()
edd = turtle.Turtle()
eddd = turtle.Turtle()
edddd = turtle.Turtle()
eddddd = turtle.Turtle()
edddddd = turtle.Turtle()
eddddddd= turtle.Turtle()

ed.shape("turtle")
edd.shape("turtle")
eddd.shape("turtle")
edddd.shape("turtle")
eddddd.shape("turtle")
eddddd.shape("turtle")
edddddd.shape("turtle")

ed.penup()
ed.begin_fill()
ed.color("green")
ed.forward(500)
ed.backward(1000)
ed.right(450)
ed.forward(500)
ed.right(270)
ed.forward(1000)
ed.left(90)
ed.forward(500)
ed.end_fill()
ed.pendown()

edd.penup()
edd.begin_fill()
edd.color("sky blue")
edd.forward(500)
edd.left(90)
edd.forward(1000)
edd.left(90)
edd.forward(1000)
edd.left(90)
edd.forward(500)
edd.forward(500)
edd.end_fill()
edd.pendown()

eddd.penup()
eddd.begin_fill()
eddd.color("saddle brown")
eddd.goto(350, 0)
eddd.left(90)
eddd.forward(250)
eddd.right(90)
eddd.forward(50)
eddd.right(90)
eddd.forward(250)
eddd.end_fill()
eddd.pendown()

edddd.penup()
edddd.begin_fill()
edddd.color("green")
edddd.goto(375, 210)
edddd.circle(100)
edddd.end_fill()

eddddd.penup()
eddddd.begin_fill()
eddddd.color("yellow")
eddddd.goto(-450, 300)
eddddd.circle(200)
eddddd.end_fill()

eddddddd.penup()
eddddddd.begin_fill()
eddddddd.color("blue")
eddddddd.goto(-150, -250)
eddddddd.circle(100)
eddddddd.end_fill()
eddddddd.pendown()

edddddd.penup()
edddddd.begin_fill()
edddddd.color("black")
edddddd.goto(-200, 0)
edddddd.left(90)
edddddd.forward(250)
edddddd.right(90)
edddddd.forward(10)
edddddd.right(90)
edddddd.forward(250)
edddddd.end_fill()
edddddd.pendown()

edddddd.penup()
edddddd.begin_fill()
edddddd.color("blue")
edddddd.goto(-200, 250)
edddddd.left(90)
edddddd.forward(100)
edddddd.left(90)
edddddd.forward(75)
edddddd.left(90)
edddddd.forward(100)
edddddd.right(90)
edddddd.backward(75)
edddddd.end_fill()
edddddd.pendown()

ed.penup()
ed.begin_fill()
ed.color("grey")
ed.goto(0, 0)
ed.forward(150)
ed.right(90)
ed.forward(150)
ed.right(90)
ed.forward(150)
ed.end_fill()
ed.pendown()



turtle.exitonclick()